services:
  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --requirepass 123
    restart: always

  postgres:
    image: postgres:18
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_DB: vidaplus_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "1234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/vidaplus_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: "123"
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - postgres

volumes:
  postgres_data: